apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: database-claim0
  name: database-claim1
  namespace: newsgac
spec:
  storageClassName: nutanix-volume
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
