apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: newsgac-claim0
  name: newsgac-claim0
  namespace: newsgac
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
