---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: newsgac
  namespace: newsgac
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 30m
spec:
  rules:
    - host: newsgac.clariah.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 5050

# TLS is handled by outside proxy